# Generated by Django 2.2.12 on 2020-09-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200924_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/default/default.jpg', upload_to='profile_pics'),
        ),
    ]
