# Generated by Django 2.2.12 on 2020-09-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200927_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
