# Generated by Django 2.2.12 on 2020-09-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200927_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
