# Generated by Django 2.2.12 on 2020-09-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200927_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
