# Generated by Django 2.2.12 on 2020-09-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20200928_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.Comment'),
        ),
    ]
