# Generated by Django 2.2.12 on 2020-09-29 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20200929_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.GameNews'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
