# Generated by Django 2.2.12 on 2020-10-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
