# Generated by Django 2.2.12 on 2020-09-06 15:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('year_of_issue', models.DateField()),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Shooter', 'Shooter'), ('Adventure', 'Adventure'), ('survival', 'Survival'), ('Open world', 'Open world'), ('Horror', 'Horror'), ('Stealth', 'Stealth'), ('Racing', 'Racing'), ('RPG', 'RPG'), ('Arcade', 'Arcade'), ('Strategy', 'Strategy'), ('Simulator', 'Simulator'), ('Puzle', 'Puzle'), ('Sport', 'sport')], max_length=108)),
                ('developer', models.CharField(max_length=60)),
                ('publisher', models.CharField(max_length=60)),
                ('version', models.CharField(max_length=60)),
                ('repack_author', models.CharField(max_length=60)),
                ('interface_language', models.CharField(max_length=60)),
                ('voice_Language', models.CharField(max_length=60)),
                ('subtitles', models.CharField(max_length=60)),
                ('Tablet', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=400)),
                ('repack', models.TextField(max_length=400)),
                ('min_os', models.CharField(max_length=30)),
                ('min_processor', models.CharField(max_length=30)),
                ('min_memory', models.CharField(max_length=30)),
                ('min_graphics', models.CharField(max_length=30)),
                ('min_storage', models.CharField(max_length=30)),
                ('min_sound_card', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
                ('processor', models.CharField(max_length=30)),
                ('memory', models.CharField(max_length=30)),
                ('graphics', models.CharField(max_length=30)),
                ('storage', models.CharField(max_length=30)),
                ('sound_card', models.CharField(max_length=30)),
                ('main_image', models.ImageField(upload_to='')),
                ('news_image1', models.ImageField(upload_to='')),
                ('news_image2', models.ImageField(upload_to='')),
                ('news_image3', models.ImageField(upload_to='')),
                ('news_image4', models.ImageField(upload_to='')),
                ('video_trailer', models.CharField(max_length=50)),
                ('video_gameplay', models.CharField(max_length=50)),
            ],
        ),
    ]
