# Generated by Django 2.2.12 on 2020-09-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200907_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenews',
            name='genre',
        ),
    ]
