# Generated by Django 2.2.12 on 2020-09-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_gamenews_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='genres',
            field=models.ManyToManyField(related_name='category', to='main.Genre'),
        ),
    ]
