# Generated by Django 2.2.12 on 2020-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200908_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='repack',
            field=models.TextField(max_length=1000),
        ),
    ]
