# Generated by Django 2.2.12 on 2020-09-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200909_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='genres',
            field=models.ManyToManyField(to='main.Genre'),
        ),
    ]
