# Generated by Django 2.2.12 on 2020-09-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200913_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
