# Generated by Django 2.2.12 on 2020-09-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='specifications',
            field=models.FileField(default=1, upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
