# Generated by Django 2.2.12 on 2020-09-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_gamenews_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenews',
            name='specifications',
        ),
    ]
