# Generated by Django 2.2.12 on 2020-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_gamenews_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='data',
            field=models.FileField(upload_to='torrent-files'),
        ),
    ]
