# Generated by Django 2.2.12 on 2020-09-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200915_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
