# Generated by Django 2.2.12 on 2020-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200916_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenews',
            name='genres',
        ),
        migrations.AddField(
            model_name='gamenews',
            name='genres',
            field=models.ManyToManyField(to='main.Genre'),
        ),
    ]
