# Generated by Django 2.2.12 on 2020-09-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200916_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpComingGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=1000)),
                ('main_image', models.ImageField(upload_to='')),
                ('news_image1', models.ImageField(upload_to='')),
                ('news_image2', models.ImageField(upload_to='')),
                ('news_image3', models.ImageField(upload_to='')),
                ('news_image4', models.ImageField(upload_to='')),
                ('video_trailer', models.CharField(max_length=50)),
            ],
        ),
    ]
