# Generated by Django 2.2.12 on 2020-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_upcominggames_main_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='Hot_News',
            field=models.BooleanField(default=False),
        ),
    ]
