# Generated by Django 2.2.12 on 2020-09-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
