# Generated by Django 2.2.12 on 2020-09-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
