# Generated by Django 2.2.12 on 2020-10-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_gamenews_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='news_views',
            field=models.IntegerField(default=0),
        ),
    ]
