# Generated by Django 2.2.12 on 2020-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_gamenews_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenews',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='gamenews',
            name='news_views',
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='graphics',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='memory',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_graphics',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_memory',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_os',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_processor',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_sound_card',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_storage',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='os',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='processor',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='sound_card',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='storage',
            field=models.CharField(max_length=60),
        ),
    ]
