# Generated by Django 2.2.12 on 2020-10-08 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0038_gamenews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
