# Generated by Django 2.2.12 on 2020-10-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_gamenews_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenews',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='gamenews',
            name='slug',
        ),
    ]
