# Generated by Django 2.2.12 on 2020-10-08 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_auto_20201008_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
