# Generated by Django 2.2.12 on 2020-10-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_gamenews_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamenews',
            old_name='Tablet',
            new_name='tablet',
        ),
    ]
