# Generated by Django 2.2.12 on 2020-10-14 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0043_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo_image',
            field=models.ImageField(upload_to='logo_image'),
        ),
    ]
