# Generated by Django 2.2.12 on 2020-10-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20201016_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
