# Generated by Django 2.2.12 on 2020-10-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20201016_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamenews',
            old_name='download_count',
            new_name='download',
        ),
    ]
