# Generated by Django 2.2.12 on 2020-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20201016_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenews',
            name='download',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
