# Generated by Django 2.2.12 on 2020-10-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_gamenews_games_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenews',
            name='sound_card',
        ),
    ]
