# Generated by Django 2.2.12 on 2020-10-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_gamenews_sound_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenews',
            name='min_sound_card',
        ),
    ]
