# Generated by Django 2.2.12 on 2020-10-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_gamenews_min_sound_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='platform',
            field=models.CharField(default=1, max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='developer',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='graphics',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='interface_language',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='memory',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_graphics',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_memory',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_os',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_processor',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='min_storage',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='os',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='processor',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='publisher',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='repack',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='repack_author',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='storage',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='subtitles',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='tablet',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='title',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='version',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='voice_Language',
            field=models.CharField(max_length=130),
        ),
    ]
